services:
    backend:
        build:
            context: .
            target: dev  # prod
        env_file:
            - .env
        environment:
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}
            GO_URL: ${GO_URL}
            GO_USERNAME: ${GO_USERNAME}
            GO_PASSWORD: ${GO_PASSWORD}
            GO_NOTEBOOK_ID: ${GO_NOTEBOOK_ID}
        ports:
            - 8000:8000
        volumes:
            # - omaha_db:/app/db
            - ./src:/app/src
            - ./db:/app/db

# volumes:
#     omaha_db:
#         name: omaha_db_volume
