services:
    backend:
        build:
            context: .
            target: dev  # prod
        environment:
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}
        ports:
            - 8000:8000
        volumes:
            # - omaha_db:/app/db
            - ./src:/app/src
            - ./db:/app/db

# volumes:
#     omaha_db:
#         name: omaha_db_volume
